### ISSUE TITLE
importing requirements? 

### ISSUE THREAD

**Issue by woeterman94** [ether/ep_file_menu_toolbar#11]
This might be a stupid question, but does the import functionality require abiword in order to work?

**Comment by JohnMcLear** [comment]
No.

It requires abiword or libreoffice for word, pdf etc. support.  Out of the box html / text / etherpad et al all work without any deps.

**Comment by woeterman94** [comment]
Importing works great for word (I have abiword installed). 
Pdf gives weird symbols. After the import the timeslider doesn't work anymore.

**Comment by JohnMcLear** [comment]
We have test coverage so it's unliekly it's the software at fault.  Check your abiword version, thinks like if your database is properly setup..  Also check multiple PDFs and try same PDF on video.etherpad.com

**Comment by JohnMcLear** [comment]
I don't think this is a plugin issue tbh :)
